version: '3.7'
services:
  app:
    build: .
    tty: true
    ports:
      - 3005:3005
      - 5555:5555
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: mysql:5.7
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
      # - '8889:8889'
    volumes:
      - ./mysql-data:/var/lib/mysql
